# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9524f8bd8e89445cb78a62865eedf422d9da40e6f34212332ad1441b40aa7e2e6320349df2349a551b787de607a43fa53c6316afb6d58d55e3d61f502994810d

test:
  secret_key_base: 8f68fb8a961c09448e44be5b2727da70e9bab99233adbf73db6aa46a4dd0ea4a11727ab1c5a2896681a601f98de6ff10868688ebf13b34a8d0dd9c5bcc4b66c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
